import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCircleXmark,
  faSquare,
  faEye,
  faEyeSlash,
  faCircleUser,
  faCreditCard,
  faCircle,
  faCircleCheck,
  faCalendar,
  faClock,
  faBell,
  faUser,
} from "@fortawesome/free-regular-svg-icons";
import {
  faCircleXmark as fasCircleXmark,
  faCirclePlus as fasCirclePlus,
  faUserGroup as fasUserGroup,
  faArrowRightFromBracket as fasArrowRightFromBracket,
  faPen as fasPen,

  faBars as fasBars,
  faXmark as fasXmark,
  faLink as fasLink,
  faGlobe as fasGlobe,
  faCirclePause as fasCirclePause,
  faPhone as fasPhone,
  faChevronDown as fasChevronDown,
  faChevronUp as fasChevronUp,
  faCirclePlay as fasCirclePlay,
  faChevronLeft as fasChevronLeft,
  faChevronRight as fasChevronRight,
  faCheck as fasCheck,
  faEllipsisVertical as fasEllipsisVertical,
  faGear as fasGear,
  faEllipsis as fasEllipsis,
  faMedal as fasMedal,
  faCartShopping as fasCartShopping,
  faTrashCan as fasTrashCan,
  faPlus as fasPlus,
  faBell as fasBell,
  faUser as fasUser,
  faVideo as fasVideo,
  faServer as fasServer,
  faEnvelope as fasEnvelope,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  //Regular Icons
  faCircleXmark,
  faSquare,
  faEye,
  faEyeSlash,
  faCircleUser,
  faCreditCard,
  faCircle,
  faCircleCheck,
  faCalendar,
  faClock,
  faBell,
  faUser,
  //Solid Icons
  fasCircleXmark,
  fasCirclePlus,
  fasUserGroup,
  fasArrowRightFromBracket,
  fasPen,
  fasChevronDown,
  fasChevronUp,
  fasChevronLeft,
  fasChevronRight,
  fasBars,
  fasXmark,
  fasLink,
  fasGlobe,
  fasCirclePause,
  fasPhone,
  fasCirclePlay,
  fasCheck,
  fasEllipsisVertical,
  fasGear,
  fasEllipsis,
  fasMedal,
  fasCartShopping,
  fasTrashCan,
  fasPlus,
  fasBell,
  fasUser,
  fasVideo,
  fasServer,
  fasEnvelope,
);
